# Bird Finder App - DBT Project Configuration
# This project transforms raw eBird API data into analytics-ready models

name: 'bird_finder_transformations'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bird_finder'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  dbt-osmosis:
    ebirdapi:
      path: "sources/ebirdapi/source.yml"
      schema: "ebirdapi_data"

models:
  bird_finder_transformations:
    +dbt-osmosis: "docs/{model}.yml"
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    dimensions:
      +materialized: table
      +docs:
        node_color: "lightgreen"
    facts:
      +materialized: table
      +docs:
        node_color: "orange"
